
#define VERSION "0.42.0"
#define TRAVERSO_DEFINES "-DSTATIC_BUILD;-DUSE_DEBUGGER;-DQT_OPENGL_SUPPORT;-DLV2_SUPPORT;-DMP3_DECODE_SUPPORT;-DHAVE_SYS_VFS_H;-DHAVE_SYS_STAT_H"

/* #undef BUILD_MAC_BUNDLE */
